# Generated by Django 2.0.1 on 2019-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regandloginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='pwd',
        ),
        migrations.AddField(
            model_name='reg',
            name='cpassword',
            field=models.CharField(default='lokeshit', max_length=20),
        ),
        migrations.AddField(
            model_name='reg',
            name='emailid',
            field=models.EmailField(default='lokeshitinfo@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='reg',
            name='password',
            field=models.CharField(default='lokeshit', max_length=20),
        ),
    ]
